#! /usr/bin/env bash

dir="$HOME/.config/rofi/style.rasi"

function tmux_sessions() {
    tmux list-session -F '#S'
}

TMUX_SESSION=$( (echo new; tmux_sessions) | rofi -dmenu -theme "$dir" -p "TMUX: ")

if [[ "new" = "${TMUX_SESSION}" ]]; then
    alacritty -e tmux new-session &
elif [[ -z "${TMUX_SESSION}" ]]; then
    echo "Nothing to do"
else
  ok=$(tmux_sessions | grep $TMUX_SESSION)
  if [[ -z $ok ]]; then
    echo "No such session"
  else
    alacritty -e tmux -u -f ~/.tmux.conf attach -t "${TMUX_SESSION}" &
  fi
fi
