after-login-command = []
after-startup-command = []
exec-on-workspace-change = []
on-focus-changed = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# stack layout padding
accordion-padding = 0
default-root-container-layout = 'accordion'
default-root-container-orientation = 'auto'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[workspace-to-monitor-force-assignment]
    1 = 'main'                       # Main monitor
    2 = 'main'                       # Main monitor
    3 = 'main'                       # Main monitor
    4 = 'main'                       # Main monitor
    5 = 'main'                       # Main monitor
    6 = '^built-in retina display$'  # Case insensitive regex match

[mode.main.binding]
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # See: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'

    alt-left = 'workspace --wrap-around prev'
    alt-right = 'workspace --wrap-around next'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'
    alt-semicolon = 'mode service'

    cmd-down = 'volume down'
    cmd-up = 'volume up'

    alt-f = 'macos-native-fullscreen'
    cmd-q = 'close'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    shift-down = ['volume set 0', 'mode main']

# Assign apps to workspaces

# Main screen
[[on-window-detected]]
    if.app-id = 'org.mozilla.firefox'
    run = 'move-node-to-workspace 1'

[[on-window-detected]]
    if.app-id = 'com.google.Chrome'
    run = 'move-node-to-workspace 1'

[[on-window-detected]]
    if.app-id = 'com.todesktop.230313mzl4w4u92' # Cursor
    run = 'move-node-to-workspace 2'

[[on-window-detected]]
    if.app-id = 'com.googlecode.iterm2'
    run = 'move-node-to-workspace 3'

[[on-window-detected]]
    if.app-id = 'com.github.wez.wezterm'
    run = 'move-node-to-workspace 3'

# Secondary screen
[[on-window-detected]]
    if.app-id = 'us.zoom.xos'
    run = 'move-node-to-workspace 6'

[[on-window-detected]]
    if.app-id = 'com.spotify.client'
    run = 'move-node-to-workspace 6'
