#--------------BASICS--------------#

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

#--CHARACTER MODULE
[character]
success_symbol = "[󰬐](bold green)"
error_symbol   = "[󰬐](bold red)"
vicmd_symbol   = "[󰬕](blue)"
vimcmd_replace_one_symbol = "[󰬙](red)"
vimcmd_replace_symbol = "[󰬙](red)"
vimcmd_visual_symbol = "[󰬝](yellow)"

#--CMD DURATION
[cmd_duration]
show_notifications=true
style = "bold red"
format = " [$duration]($style) "

#--------------LANGUAGES--------------#

[python]
symbol = ""

[rust]
symbol = ""
style = ""

#--------------GIT STUFF--------------#
[git_branch]
symbol = " "

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
conflicted = "(red) "
ahead = "[ ${count}](blue) "
behind = "[ ${count}](bold red) "
untracked = "[ ${count}](yellow) "
stashed = "[󱑤 ](purple) "
modified = "[󱍸 ${count}](blue) "
staged = "[ ${count}](orange) "
renamed = "[󰛿 ${count}](bold red) "
deleted = "[󰚃 ${count}](red) "


#--------------RANDOM--------------#

[custom.vid]
description = "to show vlc icon to folders containing vid files"
shell = ['bash']
command = "echo 󰕼 "
style = "#D08770"
extensions = ["mp4","mkv","webm"]
format = "[$output]($style)"
