#--------------BASICS--------------#

# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

#--CHARACTER MODULE
[character]
success_symbol = "[INS](bold green)"
error_symbol   = "[INS](bold red)"
vicmd_symbol   = "[NOR](bold blue)"
vimcmd_replace_one_symbol = "[REP](bold red)"
vimcmd_replace_symbol = "[REP](bold red)"
vimcmd_visual_symbol = "[VIS](bold yellow)"

#--CMD DURATION
[cmd_duration]
show_notifications=true
style = "bold red"
format = " [$duration]($style) "

# --Package Versioning
[package]
format='[ ](dimmed black) [$symbol$version]($style) '
symbol=" "

#--------------LANGUAGES--------------#

[python]
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = ""

#--------------GIT STUFF--------------#
[git_branch]
symbol = " "

[git_status]
format = '([\[ $all_status$ahead_behind\]]($style) )'
conflicted = "(red) "
ahead = "[ ${count}](blue) "
behind = "[ ${count}](bold red) "
untracked = "[ ${count}](yellow) "
stashed = "[󱑤 ](purple) "
modified = "[󱍸 ${count}](blue) "
staged = "[ ${count}](orange) "
renamed = "[󰛿 ${count}](bold red) "
deleted = "[󰚃 ${count}](red) "


#--------------RANDOM--------------#

[custom.vid]
description = "to show vlc icon to folders containing vid files"
shell = ['bash']
command = "echo 󰕼 "
style = "#D08770"
extensions = ["mp4","mkv","webm"]
format = "[$output]($style)"
